/*
Netlify's API documentation

Netlify is a hosting service for the programmable web. It understands your documents and provides an API to handle atomic deploys of websites, manage form submissions, inject JavaScript snippets, and much more. This is a REST-style API that uses JSON for serialization and OAuth 2 for authentication.   This document is an OpenAPI reference for the Netlify API that you can explore. For more detailed instructions for common uses, please visit the [online documentation](https://www.netlify.com/docs/api/). Visit our Community forum to join the conversation about [understanding and using Netlify's API](https://community.netlify.com/t/common-issue-understanding-and-using-netlifys-api/160).   Additionally, we have two API clients for your convenience: - [Go Client](https://github.com/netlify/open-api#go-client) - [JS Client](https://github.com/netlify/build/tree/main/packages/js-client) 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netlifyapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the SlackWorkspace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlackWorkspace{}

// SlackWorkspace struct for SlackWorkspace
type SlackWorkspace struct {
	// The ID of the Workspace
	Id string `json:"id"`
	// The name of the Workspace
	Name string `json:"name"`
	// The Slack ID of the Workspace
	SlackTeamId string `json:"slack_team_id"`
	// The cooldown datetime for the Workspace
	CooldownUntil *time.Time `json:"cooldown_until,omitempty"`
	// The billing tier of the Workspace
	Plan *string `json:"plan,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SlackWorkspace SlackWorkspace

// NewSlackWorkspace instantiates a new SlackWorkspace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlackWorkspace(id string, name string, slackTeamId string) *SlackWorkspace {
	this := SlackWorkspace{}
	this.Id = id
	this.Name = name
	this.SlackTeamId = slackTeamId
	return &this
}

// NewSlackWorkspaceWithDefaults instantiates a new SlackWorkspace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlackWorkspaceWithDefaults() *SlackWorkspace {
	this := SlackWorkspace{}
	return &this
}

// GetId returns the Id field value
func (o *SlackWorkspace) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SlackWorkspace) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SlackWorkspace) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *SlackWorkspace) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SlackWorkspace) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SlackWorkspace) SetName(v string) {
	o.Name = v
}

// GetSlackTeamId returns the SlackTeamId field value
func (o *SlackWorkspace) GetSlackTeamId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SlackTeamId
}

// GetSlackTeamIdOk returns a tuple with the SlackTeamId field value
// and a boolean to check if the value has been set.
func (o *SlackWorkspace) GetSlackTeamIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SlackTeamId, true
}

// SetSlackTeamId sets field value
func (o *SlackWorkspace) SetSlackTeamId(v string) {
	o.SlackTeamId = v
}

// GetCooldownUntil returns the CooldownUntil field value if set, zero value otherwise.
func (o *SlackWorkspace) GetCooldownUntil() time.Time {
	if o == nil || IsNil(o.CooldownUntil) {
		var ret time.Time
		return ret
	}
	return *o.CooldownUntil
}

// GetCooldownUntilOk returns a tuple with the CooldownUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlackWorkspace) GetCooldownUntilOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CooldownUntil) {
		return nil, false
	}
	return o.CooldownUntil, true
}

// HasCooldownUntil returns a boolean if a field has been set.
func (o *SlackWorkspace) HasCooldownUntil() bool {
	if o != nil && !IsNil(o.CooldownUntil) {
		return true
	}

	return false
}

// SetCooldownUntil gets a reference to the given time.Time and assigns it to the CooldownUntil field.
func (o *SlackWorkspace) SetCooldownUntil(v time.Time) {
	o.CooldownUntil = &v
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *SlackWorkspace) GetPlan() string {
	if o == nil || IsNil(o.Plan) {
		var ret string
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlackWorkspace) GetPlanOk() (*string, bool) {
	if o == nil || IsNil(o.Plan) {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *SlackWorkspace) HasPlan() bool {
	if o != nil && !IsNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given string and assigns it to the Plan field.
func (o *SlackWorkspace) SetPlan(v string) {
	o.Plan = &v
}

func (o SlackWorkspace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SlackWorkspace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["slack_team_id"] = o.SlackTeamId
	if !IsNil(o.CooldownUntil) {
		toSerialize["cooldown_until"] = o.CooldownUntil
	}
	if !IsNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SlackWorkspace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"slack_team_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSlackWorkspace := _SlackWorkspace{}

	err = json.Unmarshal(data, &varSlackWorkspace)

	if err != nil {
		return err
	}

	*o = SlackWorkspace(varSlackWorkspace)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "slack_team_id")
		delete(additionalProperties, "cooldown_until")
		delete(additionalProperties, "plan")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSlackWorkspace struct {
	value *SlackWorkspace
	isSet bool
}

func (v NullableSlackWorkspace) Get() *SlackWorkspace {
	return v.value
}

func (v *NullableSlackWorkspace) Set(val *SlackWorkspace) {
	v.value = val
	v.isSet = true
}

func (v NullableSlackWorkspace) IsSet() bool {
	return v.isSet
}

func (v *NullableSlackWorkspace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlackWorkspace(val *SlackWorkspace) *NullableSlackWorkspace {
	return &NullableSlackWorkspace{value: val, isSet: true}
}

func (v NullableSlackWorkspace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlackWorkspace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


