/*
Netlify's API documentation

Netlify is a hosting service for the programmable web. It understands your documents and provides an API to handle atomic deploys of websites, manage form submissions, inject JavaScript snippets, and much more. This is a REST-style API that uses JSON for serialization and OAuth 2 for authentication.   This document is an OpenAPI reference for the Netlify API that you can explore. For more detailed instructions for common uses, please visit the [online documentation](https://docs.netlify.com/api/get-started/). Visit our Community forum to join the conversation about [understanding and using Netlify’s API](https://community.netlify.com/t/common-issue-understanding-and-using-netlifys-api/160).   Additionally, we have two API clients for your convenience: - [Go Client](https://github.com/netlify/open-api#go-client) - [JS Client](https://github.com/netlify/js-client) 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netlifyapi

import (
	"encoding/json"
)

// checks if the CreateSiteDeployRequestFunctionsConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSiteDeployRequestFunctionsConfig{}

// CreateSiteDeployRequestFunctionsConfig struct for CreateSiteDeployRequestFunctionsConfig
type CreateSiteDeployRequestFunctionsConfig struct {
	Name *CreateSiteDeployRequestFunctionsConfigName `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateSiteDeployRequestFunctionsConfig CreateSiteDeployRequestFunctionsConfig

// NewCreateSiteDeployRequestFunctionsConfig instantiates a new CreateSiteDeployRequestFunctionsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSiteDeployRequestFunctionsConfig() *CreateSiteDeployRequestFunctionsConfig {
	this := CreateSiteDeployRequestFunctionsConfig{}
	return &this
}

// NewCreateSiteDeployRequestFunctionsConfigWithDefaults instantiates a new CreateSiteDeployRequestFunctionsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSiteDeployRequestFunctionsConfigWithDefaults() *CreateSiteDeployRequestFunctionsConfig {
	this := CreateSiteDeployRequestFunctionsConfig{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateSiteDeployRequestFunctionsConfig) GetName() CreateSiteDeployRequestFunctionsConfigName {
	if o == nil || IsNil(o.Name) {
		var ret CreateSiteDeployRequestFunctionsConfigName
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSiteDeployRequestFunctionsConfig) GetNameOk() (*CreateSiteDeployRequestFunctionsConfigName, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateSiteDeployRequestFunctionsConfig) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given CreateSiteDeployRequestFunctionsConfigName and assigns it to the Name field.
func (o *CreateSiteDeployRequestFunctionsConfig) SetName(v CreateSiteDeployRequestFunctionsConfigName) {
	o.Name = &v
}

func (o CreateSiteDeployRequestFunctionsConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSiteDeployRequestFunctionsConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateSiteDeployRequestFunctionsConfig) UnmarshalJSON(data []byte) (err error) {
	varCreateSiteDeployRequestFunctionsConfig := _CreateSiteDeployRequestFunctionsConfig{}

	err = json.Unmarshal(data, &varCreateSiteDeployRequestFunctionsConfig)

	if err != nil {
		return err
	}

	*o = CreateSiteDeployRequestFunctionsConfig(varCreateSiteDeployRequestFunctionsConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateSiteDeployRequestFunctionsConfig struct {
	value *CreateSiteDeployRequestFunctionsConfig
	isSet bool
}

func (v NullableCreateSiteDeployRequestFunctionsConfig) Get() *CreateSiteDeployRequestFunctionsConfig {
	return v.value
}

func (v *NullableCreateSiteDeployRequestFunctionsConfig) Set(val *CreateSiteDeployRequestFunctionsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSiteDeployRequestFunctionsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSiteDeployRequestFunctionsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSiteDeployRequestFunctionsConfig(val *CreateSiteDeployRequestFunctionsConfig) *NullableCreateSiteDeployRequestFunctionsConfig {
	return &NullableCreateSiteDeployRequestFunctionsConfig{value: val, isSet: true}
}

func (v NullableCreateSiteDeployRequestFunctionsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSiteDeployRequestFunctionsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


