/*
Netlify's API documentation

Netlify is a hosting service for the programmable web. It understands your documents and provides an API to handle atomic deploys of websites, manage form submissions, inject JavaScript snippets, and much more. This is a REST-style API that uses JSON for serialization and OAuth 2 for authentication.   This document is an OpenAPI reference for the Netlify API that you can explore. For more detailed instructions for common uses, please visit the [online documentation](https://docs.netlify.com/api/get-started/). Visit our Community forum to join the conversation about [understanding and using Netlify’s API](https://community.netlify.com/t/common-issue-understanding-and-using-netlifys-api/160).   Additionally, we have two API clients for your convenience: - [Go Client](https://github.com/netlify/open-api#go-client) - [JS Client](https://github.com/netlify/js-client) 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netlifyapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the Organization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Organization{}

// Organization Organization model definition
type Organization struct {
	// The slug for the organization, a normalized internal identifier for use in places like URLs
	Slug string `json:"slug"`
	// The organization ID
	Id string `json:"id"`
	// The name for the organization
	Name string `json:"name"`
	// When the organization was created
	CreatedAt time.Time `json:"created_at"`
	// When the organization was updated
	UpdatedAt time.Time `json:"updated_at"`
	// The billing email for the organization
	BillingEmail string `json:"billing_email"`
	// The logo url of the organization
	LogoUrl string `json:"logo_url"`
	// Billing Period
	BillingPeriod string `json:"billing_period"`
	// Whether the organization uses invoices
	Invoicing bool `json:"invoicing"`
	// The number of days to pay the invoice; Only applies to organizations where invoicing is true.  Value values: *30*, *60*, *null*, defaults to 30.
	PaymentTerm int64 `json:"payment_term"`
	// The payment method ID
	PaymentMethodId string `json:"payment_method_id"`
	// Whether the organization uses Zuora sandbox
	Sandbox bool `json:"sandbox"`
	// The bill cycle day of the month for the Zuora account
	BillCycleDay int64 `json:"bill_cycle_day"`
	// When the current contract starts
	ContractStartDate time.Time `json:"contract_start_date"`
	// When the current contract ends
	ContractEndDate time.Time `json:"contract_end_date"`
	// The contract term length in months
	ContractTermMonths int64 `json:"contract_term_months"`
	// Whether the enterprise subscription automatically renews at the end of its term in Zuora
	AutoRenew bool `json:"auto_renew"`
	// The purchase order number
	PurchaseOrder string `json:"purchase_order"`
	// The first name to show on invoice
	FirstName string `json:"first_name"`
	// The last name to show on invoice
	LastName string `json:"last_name"`
	// The company name to show on invoice
	CompanyName string `json:"company_name"`
	// The first address line to show on invoice
	Address1 string `json:"address1"`
	// The second address line to show on invoice
	Address2 string `json:"address2"`
	// The city to show on invoice
	City string `json:"city"`
	// The state to show on invoice
	State string `json:"state"`
	// The postal code to show on invoice
	PostalCode string `json:"postal_code"`
	// The country to show on invoice
	Country string `json:"country"`
	// Whether the organization has configured sso
	SamlEnabled bool `json:"saml_enabled"`
	// Determines type of saml enforcement
	EnforceSaml NullableString `json:"enforce_saml"`
	// Determines type of mfa enforcement
	EnforceMfa NullableString `json:"enforce_mfa"`
	Capabilities map[string]interface{} `json:"capabilities"`
	// Whether the organization allows Netlify support to access their account via UI
	SupportAdministrationEnabled bool `json:"support_administration_enabled"`
	// When the organization connected to directory sync
	DirectorySyncConnectedAt NullableTime `json:"directory_sync_connected_at"`
	// When the organization activated directory sync
	DirectorySyncActivatedAt NullableTime `json:"directory_sync_activated_at"`
	// When the organization deactivated directory sync
	DirectorySyncDeactivatedAt NullableTime `json:"directory_sync_deactivated_at"`
	// When the organization deleted directory sync
	DirectorySyncDeletedAt NullableTime `json:"directory_sync_deleted_at"`
	// When the organization enabled SAML
	SamlEnabledAt NullableTime `json:"saml_enabled_at"`
	// The number of team members in the organization
	TotalMemberCount int64 `json:"total_member_count"`
	AdditionalProperties map[string]interface{}
}

type _Organization Organization

// NewOrganization instantiates a new Organization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganization(slug string, id string, name string, createdAt time.Time, updatedAt time.Time, billingEmail string, logoUrl string, billingPeriod string, invoicing bool, paymentTerm int64, paymentMethodId string, sandbox bool, billCycleDay int64, contractStartDate time.Time, contractEndDate time.Time, contractTermMonths int64, autoRenew bool, purchaseOrder string, firstName string, lastName string, companyName string, address1 string, address2 string, city string, state string, postalCode string, country string, samlEnabled bool, enforceSaml NullableString, enforceMfa NullableString, capabilities map[string]interface{}, supportAdministrationEnabled bool, directorySyncConnectedAt NullableTime, directorySyncActivatedAt NullableTime, directorySyncDeactivatedAt NullableTime, directorySyncDeletedAt NullableTime, samlEnabledAt NullableTime, totalMemberCount int64) *Organization {
	this := Organization{}
	this.Slug = slug
	this.Id = id
	this.Name = name
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.BillingEmail = billingEmail
	this.LogoUrl = logoUrl
	this.BillingPeriod = billingPeriod
	this.Invoicing = invoicing
	this.PaymentTerm = paymentTerm
	this.PaymentMethodId = paymentMethodId
	this.Sandbox = sandbox
	this.BillCycleDay = billCycleDay
	this.ContractStartDate = contractStartDate
	this.ContractEndDate = contractEndDate
	this.ContractTermMonths = contractTermMonths
	this.AutoRenew = autoRenew
	this.PurchaseOrder = purchaseOrder
	this.FirstName = firstName
	this.LastName = lastName
	this.CompanyName = companyName
	this.Address1 = address1
	this.Address2 = address2
	this.City = city
	this.State = state
	this.PostalCode = postalCode
	this.Country = country
	this.SamlEnabled = samlEnabled
	this.EnforceSaml = enforceSaml
	this.EnforceMfa = enforceMfa
	this.Capabilities = capabilities
	this.SupportAdministrationEnabled = supportAdministrationEnabled
	this.DirectorySyncConnectedAt = directorySyncConnectedAt
	this.DirectorySyncActivatedAt = directorySyncActivatedAt
	this.DirectorySyncDeactivatedAt = directorySyncDeactivatedAt
	this.DirectorySyncDeletedAt = directorySyncDeletedAt
	this.SamlEnabledAt = samlEnabledAt
	this.TotalMemberCount = totalMemberCount
	return &this
}

// NewOrganizationWithDefaults instantiates a new Organization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationWithDefaults() *Organization {
	this := Organization{}
	return &this
}

// GetSlug returns the Slug field value
func (o *Organization) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *Organization) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *Organization) SetSlug(v string) {
	o.Slug = v
}

// GetId returns the Id field value
func (o *Organization) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Organization) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Organization) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Organization) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Organization) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Organization) SetName(v string) {
	o.Name = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Organization) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Organization) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Organization) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Organization) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Organization) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Organization) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetBillingEmail returns the BillingEmail field value
func (o *Organization) GetBillingEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BillingEmail
}

// GetBillingEmailOk returns a tuple with the BillingEmail field value
// and a boolean to check if the value has been set.
func (o *Organization) GetBillingEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingEmail, true
}

// SetBillingEmail sets field value
func (o *Organization) SetBillingEmail(v string) {
	o.BillingEmail = v
}

// GetLogoUrl returns the LogoUrl field value
func (o *Organization) GetLogoUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LogoUrl
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value
// and a boolean to check if the value has been set.
func (o *Organization) GetLogoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogoUrl, true
}

// SetLogoUrl sets field value
func (o *Organization) SetLogoUrl(v string) {
	o.LogoUrl = v
}

// GetBillingPeriod returns the BillingPeriod field value
func (o *Organization) GetBillingPeriod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BillingPeriod
}

// GetBillingPeriodOk returns a tuple with the BillingPeriod field value
// and a boolean to check if the value has been set.
func (o *Organization) GetBillingPeriodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingPeriod, true
}

// SetBillingPeriod sets field value
func (o *Organization) SetBillingPeriod(v string) {
	o.BillingPeriod = v
}

// GetInvoicing returns the Invoicing field value
func (o *Organization) GetInvoicing() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Invoicing
}

// GetInvoicingOk returns a tuple with the Invoicing field value
// and a boolean to check if the value has been set.
func (o *Organization) GetInvoicingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Invoicing, true
}

// SetInvoicing sets field value
func (o *Organization) SetInvoicing(v bool) {
	o.Invoicing = v
}

// GetPaymentTerm returns the PaymentTerm field value
func (o *Organization) GetPaymentTerm() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PaymentTerm
}

// GetPaymentTermOk returns a tuple with the PaymentTerm field value
// and a boolean to check if the value has been set.
func (o *Organization) GetPaymentTermOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentTerm, true
}

// SetPaymentTerm sets field value
func (o *Organization) SetPaymentTerm(v int64) {
	o.PaymentTerm = v
}

// GetPaymentMethodId returns the PaymentMethodId field value
func (o *Organization) GetPaymentMethodId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentMethodId
}

// GetPaymentMethodIdOk returns a tuple with the PaymentMethodId field value
// and a boolean to check if the value has been set.
func (o *Organization) GetPaymentMethodIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentMethodId, true
}

// SetPaymentMethodId sets field value
func (o *Organization) SetPaymentMethodId(v string) {
	o.PaymentMethodId = v
}

// GetSandbox returns the Sandbox field value
func (o *Organization) GetSandbox() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Sandbox
}

// GetSandboxOk returns a tuple with the Sandbox field value
// and a boolean to check if the value has been set.
func (o *Organization) GetSandboxOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sandbox, true
}

// SetSandbox sets field value
func (o *Organization) SetSandbox(v bool) {
	o.Sandbox = v
}

// GetBillCycleDay returns the BillCycleDay field value
func (o *Organization) GetBillCycleDay() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.BillCycleDay
}

// GetBillCycleDayOk returns a tuple with the BillCycleDay field value
// and a boolean to check if the value has been set.
func (o *Organization) GetBillCycleDayOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillCycleDay, true
}

// SetBillCycleDay sets field value
func (o *Organization) SetBillCycleDay(v int64) {
	o.BillCycleDay = v
}

// GetContractStartDate returns the ContractStartDate field value
func (o *Organization) GetContractStartDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ContractStartDate
}

// GetContractStartDateOk returns a tuple with the ContractStartDate field value
// and a boolean to check if the value has been set.
func (o *Organization) GetContractStartDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractStartDate, true
}

// SetContractStartDate sets field value
func (o *Organization) SetContractStartDate(v time.Time) {
	o.ContractStartDate = v
}

// GetContractEndDate returns the ContractEndDate field value
func (o *Organization) GetContractEndDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ContractEndDate
}

// GetContractEndDateOk returns a tuple with the ContractEndDate field value
// and a boolean to check if the value has been set.
func (o *Organization) GetContractEndDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractEndDate, true
}

// SetContractEndDate sets field value
func (o *Organization) SetContractEndDate(v time.Time) {
	o.ContractEndDate = v
}

// GetContractTermMonths returns the ContractTermMonths field value
func (o *Organization) GetContractTermMonths() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ContractTermMonths
}

// GetContractTermMonthsOk returns a tuple with the ContractTermMonths field value
// and a boolean to check if the value has been set.
func (o *Organization) GetContractTermMonthsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractTermMonths, true
}

// SetContractTermMonths sets field value
func (o *Organization) SetContractTermMonths(v int64) {
	o.ContractTermMonths = v
}

// GetAutoRenew returns the AutoRenew field value
func (o *Organization) GetAutoRenew() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AutoRenew
}

// GetAutoRenewOk returns a tuple with the AutoRenew field value
// and a boolean to check if the value has been set.
func (o *Organization) GetAutoRenewOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AutoRenew, true
}

// SetAutoRenew sets field value
func (o *Organization) SetAutoRenew(v bool) {
	o.AutoRenew = v
}

// GetPurchaseOrder returns the PurchaseOrder field value
func (o *Organization) GetPurchaseOrder() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PurchaseOrder
}

// GetPurchaseOrderOk returns a tuple with the PurchaseOrder field value
// and a boolean to check if the value has been set.
func (o *Organization) GetPurchaseOrderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PurchaseOrder, true
}

// SetPurchaseOrder sets field value
func (o *Organization) SetPurchaseOrder(v string) {
	o.PurchaseOrder = v
}

// GetFirstName returns the FirstName field value
func (o *Organization) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *Organization) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *Organization) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value
func (o *Organization) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *Organization) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *Organization) SetLastName(v string) {
	o.LastName = v
}

// GetCompanyName returns the CompanyName field value
func (o *Organization) GetCompanyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value
// and a boolean to check if the value has been set.
func (o *Organization) GetCompanyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyName, true
}

// SetCompanyName sets field value
func (o *Organization) SetCompanyName(v string) {
	o.CompanyName = v
}

// GetAddress1 returns the Address1 field value
func (o *Organization) GetAddress1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address1
}

// GetAddress1Ok returns a tuple with the Address1 field value
// and a boolean to check if the value has been set.
func (o *Organization) GetAddress1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address1, true
}

// SetAddress1 sets field value
func (o *Organization) SetAddress1(v string) {
	o.Address1 = v
}

// GetAddress2 returns the Address2 field value
func (o *Organization) GetAddress2() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address2
}

// GetAddress2Ok returns a tuple with the Address2 field value
// and a boolean to check if the value has been set.
func (o *Organization) GetAddress2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address2, true
}

// SetAddress2 sets field value
func (o *Organization) SetAddress2(v string) {
	o.Address2 = v
}

// GetCity returns the City field value
func (o *Organization) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *Organization) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *Organization) SetCity(v string) {
	o.City = v
}

// GetState returns the State field value
func (o *Organization) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *Organization) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *Organization) SetState(v string) {
	o.State = v
}

// GetPostalCode returns the PostalCode field value
func (o *Organization) GetPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value
// and a boolean to check if the value has been set.
func (o *Organization) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostalCode, true
}

// SetPostalCode sets field value
func (o *Organization) SetPostalCode(v string) {
	o.PostalCode = v
}

// GetCountry returns the Country field value
func (o *Organization) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *Organization) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *Organization) SetCountry(v string) {
	o.Country = v
}

// GetSamlEnabled returns the SamlEnabled field value
func (o *Organization) GetSamlEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SamlEnabled
}

// GetSamlEnabledOk returns a tuple with the SamlEnabled field value
// and a boolean to check if the value has been set.
func (o *Organization) GetSamlEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SamlEnabled, true
}

// SetSamlEnabled sets field value
func (o *Organization) SetSamlEnabled(v bool) {
	o.SamlEnabled = v
}

// GetEnforceSaml returns the EnforceSaml field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Organization) GetEnforceSaml() string {
	if o == nil || o.EnforceSaml.Get() == nil {
		var ret string
		return ret
	}

	return *o.EnforceSaml.Get()
}

// GetEnforceSamlOk returns a tuple with the EnforceSaml field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Organization) GetEnforceSamlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnforceSaml.Get(), o.EnforceSaml.IsSet()
}

// SetEnforceSaml sets field value
func (o *Organization) SetEnforceSaml(v string) {
	o.EnforceSaml.Set(&v)
}

// GetEnforceMfa returns the EnforceMfa field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Organization) GetEnforceMfa() string {
	if o == nil || o.EnforceMfa.Get() == nil {
		var ret string
		return ret
	}

	return *o.EnforceMfa.Get()
}

// GetEnforceMfaOk returns a tuple with the EnforceMfa field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Organization) GetEnforceMfaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnforceMfa.Get(), o.EnforceMfa.IsSet()
}

// SetEnforceMfa sets field value
func (o *Organization) SetEnforceMfa(v string) {
	o.EnforceMfa.Set(&v)
}

// GetCapabilities returns the Capabilities field value
func (o *Organization) GetCapabilities() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value
// and a boolean to check if the value has been set.
func (o *Organization) GetCapabilitiesOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Capabilities, true
}

// SetCapabilities sets field value
func (o *Organization) SetCapabilities(v map[string]interface{}) {
	o.Capabilities = v
}

// GetSupportAdministrationEnabled returns the SupportAdministrationEnabled field value
func (o *Organization) GetSupportAdministrationEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SupportAdministrationEnabled
}

// GetSupportAdministrationEnabledOk returns a tuple with the SupportAdministrationEnabled field value
// and a boolean to check if the value has been set.
func (o *Organization) GetSupportAdministrationEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SupportAdministrationEnabled, true
}

// SetSupportAdministrationEnabled sets field value
func (o *Organization) SetSupportAdministrationEnabled(v bool) {
	o.SupportAdministrationEnabled = v
}

// GetDirectorySyncConnectedAt returns the DirectorySyncConnectedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *Organization) GetDirectorySyncConnectedAt() time.Time {
	if o == nil || o.DirectorySyncConnectedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.DirectorySyncConnectedAt.Get()
}

// GetDirectorySyncConnectedAtOk returns a tuple with the DirectorySyncConnectedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Organization) GetDirectorySyncConnectedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DirectorySyncConnectedAt.Get(), o.DirectorySyncConnectedAt.IsSet()
}

// SetDirectorySyncConnectedAt sets field value
func (o *Organization) SetDirectorySyncConnectedAt(v time.Time) {
	o.DirectorySyncConnectedAt.Set(&v)
}

// GetDirectorySyncActivatedAt returns the DirectorySyncActivatedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *Organization) GetDirectorySyncActivatedAt() time.Time {
	if o == nil || o.DirectorySyncActivatedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.DirectorySyncActivatedAt.Get()
}

// GetDirectorySyncActivatedAtOk returns a tuple with the DirectorySyncActivatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Organization) GetDirectorySyncActivatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DirectorySyncActivatedAt.Get(), o.DirectorySyncActivatedAt.IsSet()
}

// SetDirectorySyncActivatedAt sets field value
func (o *Organization) SetDirectorySyncActivatedAt(v time.Time) {
	o.DirectorySyncActivatedAt.Set(&v)
}

// GetDirectorySyncDeactivatedAt returns the DirectorySyncDeactivatedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *Organization) GetDirectorySyncDeactivatedAt() time.Time {
	if o == nil || o.DirectorySyncDeactivatedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.DirectorySyncDeactivatedAt.Get()
}

// GetDirectorySyncDeactivatedAtOk returns a tuple with the DirectorySyncDeactivatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Organization) GetDirectorySyncDeactivatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DirectorySyncDeactivatedAt.Get(), o.DirectorySyncDeactivatedAt.IsSet()
}

// SetDirectorySyncDeactivatedAt sets field value
func (o *Organization) SetDirectorySyncDeactivatedAt(v time.Time) {
	o.DirectorySyncDeactivatedAt.Set(&v)
}

// GetDirectorySyncDeletedAt returns the DirectorySyncDeletedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *Organization) GetDirectorySyncDeletedAt() time.Time {
	if o == nil || o.DirectorySyncDeletedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.DirectorySyncDeletedAt.Get()
}

// GetDirectorySyncDeletedAtOk returns a tuple with the DirectorySyncDeletedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Organization) GetDirectorySyncDeletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DirectorySyncDeletedAt.Get(), o.DirectorySyncDeletedAt.IsSet()
}

// SetDirectorySyncDeletedAt sets field value
func (o *Organization) SetDirectorySyncDeletedAt(v time.Time) {
	o.DirectorySyncDeletedAt.Set(&v)
}

// GetSamlEnabledAt returns the SamlEnabledAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *Organization) GetSamlEnabledAt() time.Time {
	if o == nil || o.SamlEnabledAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.SamlEnabledAt.Get()
}

// GetSamlEnabledAtOk returns a tuple with the SamlEnabledAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Organization) GetSamlEnabledAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.SamlEnabledAt.Get(), o.SamlEnabledAt.IsSet()
}

// SetSamlEnabledAt sets field value
func (o *Organization) SetSamlEnabledAt(v time.Time) {
	o.SamlEnabledAt.Set(&v)
}

// GetTotalMemberCount returns the TotalMemberCount field value
func (o *Organization) GetTotalMemberCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalMemberCount
}

// GetTotalMemberCountOk returns a tuple with the TotalMemberCount field value
// and a boolean to check if the value has been set.
func (o *Organization) GetTotalMemberCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalMemberCount, true
}

// SetTotalMemberCount sets field value
func (o *Organization) SetTotalMemberCount(v int64) {
	o.TotalMemberCount = v
}

func (o Organization) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Organization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["slug"] = o.Slug
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["billing_email"] = o.BillingEmail
	toSerialize["logo_url"] = o.LogoUrl
	toSerialize["billing_period"] = o.BillingPeriod
	toSerialize["invoicing"] = o.Invoicing
	toSerialize["payment_term"] = o.PaymentTerm
	toSerialize["payment_method_id"] = o.PaymentMethodId
	toSerialize["sandbox"] = o.Sandbox
	toSerialize["bill_cycle_day"] = o.BillCycleDay
	toSerialize["contract_start_date"] = o.ContractStartDate
	toSerialize["contract_end_date"] = o.ContractEndDate
	toSerialize["contract_term_months"] = o.ContractTermMonths
	toSerialize["auto_renew"] = o.AutoRenew
	toSerialize["purchase_order"] = o.PurchaseOrder
	toSerialize["first_name"] = o.FirstName
	toSerialize["last_name"] = o.LastName
	toSerialize["company_name"] = o.CompanyName
	toSerialize["address1"] = o.Address1
	toSerialize["address2"] = o.Address2
	toSerialize["city"] = o.City
	toSerialize["state"] = o.State
	toSerialize["postal_code"] = o.PostalCode
	toSerialize["country"] = o.Country
	toSerialize["saml_enabled"] = o.SamlEnabled
	toSerialize["enforce_saml"] = o.EnforceSaml.Get()
	toSerialize["enforce_mfa"] = o.EnforceMfa.Get()
	toSerialize["capabilities"] = o.Capabilities
	toSerialize["support_administration_enabled"] = o.SupportAdministrationEnabled
	toSerialize["directory_sync_connected_at"] = o.DirectorySyncConnectedAt.Get()
	toSerialize["directory_sync_activated_at"] = o.DirectorySyncActivatedAt.Get()
	toSerialize["directory_sync_deactivated_at"] = o.DirectorySyncDeactivatedAt.Get()
	toSerialize["directory_sync_deleted_at"] = o.DirectorySyncDeletedAt.Get()
	toSerialize["saml_enabled_at"] = o.SamlEnabledAt.Get()
	toSerialize["total_member_count"] = o.TotalMemberCount

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Organization) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"slug",
		"id",
		"name",
		"created_at",
		"updated_at",
		"billing_email",
		"logo_url",
		"billing_period",
		"invoicing",
		"payment_term",
		"payment_method_id",
		"sandbox",
		"bill_cycle_day",
		"contract_start_date",
		"contract_end_date",
		"contract_term_months",
		"auto_renew",
		"purchase_order",
		"first_name",
		"last_name",
		"company_name",
		"address1",
		"address2",
		"city",
		"state",
		"postal_code",
		"country",
		"saml_enabled",
		"enforce_saml",
		"enforce_mfa",
		"capabilities",
		"support_administration_enabled",
		"directory_sync_connected_at",
		"directory_sync_activated_at",
		"directory_sync_deactivated_at",
		"directory_sync_deleted_at",
		"saml_enabled_at",
		"total_member_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganization := _Organization{}

	err = json.Unmarshal(data, &varOrganization)

	if err != nil {
		return err
	}

	*o = Organization(varOrganization)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "slug")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "billing_email")
		delete(additionalProperties, "logo_url")
		delete(additionalProperties, "billing_period")
		delete(additionalProperties, "invoicing")
		delete(additionalProperties, "payment_term")
		delete(additionalProperties, "payment_method_id")
		delete(additionalProperties, "sandbox")
		delete(additionalProperties, "bill_cycle_day")
		delete(additionalProperties, "contract_start_date")
		delete(additionalProperties, "contract_end_date")
		delete(additionalProperties, "contract_term_months")
		delete(additionalProperties, "auto_renew")
		delete(additionalProperties, "purchase_order")
		delete(additionalProperties, "first_name")
		delete(additionalProperties, "last_name")
		delete(additionalProperties, "company_name")
		delete(additionalProperties, "address1")
		delete(additionalProperties, "address2")
		delete(additionalProperties, "city")
		delete(additionalProperties, "state")
		delete(additionalProperties, "postal_code")
		delete(additionalProperties, "country")
		delete(additionalProperties, "saml_enabled")
		delete(additionalProperties, "enforce_saml")
		delete(additionalProperties, "enforce_mfa")
		delete(additionalProperties, "capabilities")
		delete(additionalProperties, "support_administration_enabled")
		delete(additionalProperties, "directory_sync_connected_at")
		delete(additionalProperties, "directory_sync_activated_at")
		delete(additionalProperties, "directory_sync_deactivated_at")
		delete(additionalProperties, "directory_sync_deleted_at")
		delete(additionalProperties, "saml_enabled_at")
		delete(additionalProperties, "total_member_count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrganization struct {
	value *Organization
	isSet bool
}

func (v NullableOrganization) Get() *Organization {
	return v.value
}

func (v *NullableOrganization) Set(val *Organization) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganization) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganization(val *Organization) *NullableOrganization {
	return &NullableOrganization{value: val, isSet: true}
}

func (v NullableOrganization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


