/*
Netlify's API documentation

Netlify is a hosting service for the programmable web. It understands your documents and provides an API to handle atomic deploys of websites, manage form submissions, inject JavaScript snippets, and much more. This is a REST-style API that uses JSON for serialization and OAuth 2 for authentication.   This document is an OpenAPI reference for the Netlify API that you can explore. For more detailed instructions for common uses, please visit the [online documentation](https://docs.netlify.com/api/get-started/). Visit our Community forum to join the conversation about [understanding and using Netlify’s API](https://community.netlify.com/t/common-issue-understanding-and-using-netlifys-api/160).   Additionally, we have two API clients for your convenience: - [Go Client](https://github.com/netlify/open-api#go-client) - [JS Client](https://github.com/netlify/js-client) 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netlifyapi

import (
	"encoding/json"
)

// checks if the CreateBuildHook type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBuildHook{}

// CreateBuildHook struct for CreateBuildHook
type CreateBuildHook struct {
	// The title of the build hook
	Title *string `json:"title,omitempty"`
	// The branch of the build hook
	Branch *string `json:"branch,omitempty"`
	// If this build hook should be used to create draft deploys
	Draft *bool `json:"draft,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateBuildHook CreateBuildHook

// NewCreateBuildHook instantiates a new CreateBuildHook object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBuildHook() *CreateBuildHook {
	this := CreateBuildHook{}
	return &this
}

// NewCreateBuildHookWithDefaults instantiates a new CreateBuildHook object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBuildHookWithDefaults() *CreateBuildHook {
	this := CreateBuildHook{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateBuildHook) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBuildHook) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateBuildHook) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateBuildHook) SetTitle(v string) {
	o.Title = &v
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *CreateBuildHook) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBuildHook) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *CreateBuildHook) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *CreateBuildHook) SetBranch(v string) {
	o.Branch = &v
}

// GetDraft returns the Draft field value if set, zero value otherwise.
func (o *CreateBuildHook) GetDraft() bool {
	if o == nil || IsNil(o.Draft) {
		var ret bool
		return ret
	}
	return *o.Draft
}

// GetDraftOk returns a tuple with the Draft field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBuildHook) GetDraftOk() (*bool, bool) {
	if o == nil || IsNil(o.Draft) {
		return nil, false
	}
	return o.Draft, true
}

// HasDraft returns a boolean if a field has been set.
func (o *CreateBuildHook) HasDraft() bool {
	if o != nil && !IsNil(o.Draft) {
		return true
	}

	return false
}

// SetDraft gets a reference to the given bool and assigns it to the Draft field.
func (o *CreateBuildHook) SetDraft(v bool) {
	o.Draft = &v
}

func (o CreateBuildHook) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBuildHook) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.Draft) {
		toSerialize["draft"] = o.Draft
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateBuildHook) UnmarshalJSON(data []byte) (err error) {
	varCreateBuildHook := _CreateBuildHook{}

	err = json.Unmarshal(data, &varCreateBuildHook)

	if err != nil {
		return err
	}

	*o = CreateBuildHook(varCreateBuildHook)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "title")
		delete(additionalProperties, "branch")
		delete(additionalProperties, "draft")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateBuildHook struct {
	value *CreateBuildHook
	isSet bool
}

func (v NullableCreateBuildHook) Get() *CreateBuildHook {
	return v.value
}

func (v *NullableCreateBuildHook) Set(val *CreateBuildHook) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBuildHook) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBuildHook) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBuildHook(val *CreateBuildHook) *NullableCreateBuildHook {
	return &NullableCreateBuildHook{value: val, isSet: true}
}

func (v NullableCreateBuildHook) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBuildHook) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


