/*
Netlify's API documentation

Netlify is a hosting service for the programmable web. It understands your documents and provides an API to handle atomic deploys of websites, manage form submissions, inject JavaScript snippets, and much more. This is a REST-style API that uses JSON for serialization and OAuth 2 for authentication.   This document is an OpenAPI reference for the Netlify API that you can explore. For more detailed instructions for common uses, please visit the [online documentation](https://www.netlify.com/docs/api/). Visit our Community forum to join the conversation about [understanding and using Netlify's API](https://community.netlify.com/t/common-issue-understanding-and-using-netlifys-api/160).   Additionally, we have two API clients for your convenience: - [Go Client](https://github.com/netlify/open-api#go-client) - [JS Client](https://github.com/netlify/build/tree/main/packages/js-client) 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netlifyapi

import (
	"encoding/json"
	"fmt"
)

// checks if the DevServersSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DevServersSummary{}

// DevServersSummary DevServersSummary model definition
type DevServersSummary struct {
	AccountId string `json:"account_id"`
	ActiveDevServersCount int64 `json:"active_dev_servers_count"`
	AdditionalProperties map[string]interface{}
}

type _DevServersSummary DevServersSummary

// NewDevServersSummary instantiates a new DevServersSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDevServersSummary(accountId string, activeDevServersCount int64) *DevServersSummary {
	this := DevServersSummary{}
	this.AccountId = accountId
	this.ActiveDevServersCount = activeDevServersCount
	return &this
}

// NewDevServersSummaryWithDefaults instantiates a new DevServersSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDevServersSummaryWithDefaults() *DevServersSummary {
	this := DevServersSummary{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *DevServersSummary) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *DevServersSummary) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *DevServersSummary) SetAccountId(v string) {
	o.AccountId = v
}

// GetActiveDevServersCount returns the ActiveDevServersCount field value
func (o *DevServersSummary) GetActiveDevServersCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ActiveDevServersCount
}

// GetActiveDevServersCountOk returns a tuple with the ActiveDevServersCount field value
// and a boolean to check if the value has been set.
func (o *DevServersSummary) GetActiveDevServersCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveDevServersCount, true
}

// SetActiveDevServersCount sets field value
func (o *DevServersSummary) SetActiveDevServersCount(v int64) {
	o.ActiveDevServersCount = v
}

func (o DevServersSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DevServersSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["active_dev_servers_count"] = o.ActiveDevServersCount

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DevServersSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"active_dev_servers_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDevServersSummary := _DevServersSummary{}

	err = json.Unmarshal(data, &varDevServersSummary)

	if err != nil {
		return err
	}

	*o = DevServersSummary(varDevServersSummary)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account_id")
		delete(additionalProperties, "active_dev_servers_count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDevServersSummary struct {
	value *DevServersSummary
	isSet bool
}

func (v NullableDevServersSummary) Get() *DevServersSummary {
	return v.value
}

func (v *NullableDevServersSummary) Set(val *DevServersSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableDevServersSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableDevServersSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDevServersSummary(val *DevServersSummary) *NullableDevServersSummary {
	return &NullableDevServersSummary{value: val, isSet: true}
}

func (v NullableDevServersSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDevServersSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


