/*
Netlify's API documentation

Netlify is a hosting service for the programmable web. It understands your documents and provides an API to handle atomic deploys of websites, manage form submissions, inject JavaScript snippets, and much more. This is a REST-style API that uses JSON for serialization and OAuth 2 for authentication.   This document is an OpenAPI reference for the Netlify API that you can explore. For more detailed instructions for common uses, please visit the [online documentation](https://docs.netlify.com/api/get-started/). Visit our Community forum to join the conversation about [understanding and using Netlify’s API](https://community.netlify.com/t/common-issue-understanding-and-using-netlifys-api/160).   Additionally, we have two API clients for your convenience: - [Go Client](https://github.com/netlify/open-api#go-client) - [JS Client](https://github.com/netlify/js-client) 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netlifyapi

import (
	"encoding/json"
)

// checks if the CreateAccountFirewallConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccountFirewallConfig{}

// CreateAccountFirewallConfig struct for CreateAccountFirewallConfig
type CreateAccountFirewallConfig struct {
	Unpublished *FirewallRuleSet `json:"unpublished,omitempty"`
	Published *FirewallRuleSet `json:"published,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateAccountFirewallConfig CreateAccountFirewallConfig

// NewCreateAccountFirewallConfig instantiates a new CreateAccountFirewallConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccountFirewallConfig() *CreateAccountFirewallConfig {
	this := CreateAccountFirewallConfig{}
	return &this
}

// NewCreateAccountFirewallConfigWithDefaults instantiates a new CreateAccountFirewallConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccountFirewallConfigWithDefaults() *CreateAccountFirewallConfig {
	this := CreateAccountFirewallConfig{}
	return &this
}

// GetUnpublished returns the Unpublished field value if set, zero value otherwise.
func (o *CreateAccountFirewallConfig) GetUnpublished() FirewallRuleSet {
	if o == nil || IsNil(o.Unpublished) {
		var ret FirewallRuleSet
		return ret
	}
	return *o.Unpublished
}

// GetUnpublishedOk returns a tuple with the Unpublished field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountFirewallConfig) GetUnpublishedOk() (*FirewallRuleSet, bool) {
	if o == nil || IsNil(o.Unpublished) {
		return nil, false
	}
	return o.Unpublished, true
}

// HasUnpublished returns a boolean if a field has been set.
func (o *CreateAccountFirewallConfig) HasUnpublished() bool {
	if o != nil && !IsNil(o.Unpublished) {
		return true
	}

	return false
}

// SetUnpublished gets a reference to the given FirewallRuleSet and assigns it to the Unpublished field.
func (o *CreateAccountFirewallConfig) SetUnpublished(v FirewallRuleSet) {
	o.Unpublished = &v
}

// GetPublished returns the Published field value if set, zero value otherwise.
func (o *CreateAccountFirewallConfig) GetPublished() FirewallRuleSet {
	if o == nil || IsNil(o.Published) {
		var ret FirewallRuleSet
		return ret
	}
	return *o.Published
}

// GetPublishedOk returns a tuple with the Published field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountFirewallConfig) GetPublishedOk() (*FirewallRuleSet, bool) {
	if o == nil || IsNil(o.Published) {
		return nil, false
	}
	return o.Published, true
}

// HasPublished returns a boolean if a field has been set.
func (o *CreateAccountFirewallConfig) HasPublished() bool {
	if o != nil && !IsNil(o.Published) {
		return true
	}

	return false
}

// SetPublished gets a reference to the given FirewallRuleSet and assigns it to the Published field.
func (o *CreateAccountFirewallConfig) SetPublished(v FirewallRuleSet) {
	o.Published = &v
}

func (o CreateAccountFirewallConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAccountFirewallConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Unpublished) {
		toSerialize["unpublished"] = o.Unpublished
	}
	if !IsNil(o.Published) {
		toSerialize["published"] = o.Published
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateAccountFirewallConfig) UnmarshalJSON(data []byte) (err error) {
	varCreateAccountFirewallConfig := _CreateAccountFirewallConfig{}

	err = json.Unmarshal(data, &varCreateAccountFirewallConfig)

	if err != nil {
		return err
	}

	*o = CreateAccountFirewallConfig(varCreateAccountFirewallConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "unpublished")
		delete(additionalProperties, "published")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateAccountFirewallConfig struct {
	value *CreateAccountFirewallConfig
	isSet bool
}

func (v NullableCreateAccountFirewallConfig) Get() *CreateAccountFirewallConfig {
	return v.value
}

func (v *NullableCreateAccountFirewallConfig) Set(val *CreateAccountFirewallConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccountFirewallConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccountFirewallConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccountFirewallConfig(val *CreateAccountFirewallConfig) *NullableCreateAccountFirewallConfig {
	return &NullableCreateAccountFirewallConfig{value: val, isSet: true}
}

func (v NullableCreateAccountFirewallConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccountFirewallConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


