/*
Netlify's API documentation

Netlify is a hosting service for the programmable web. It understands your documents and provides an API to handle atomic deploys of websites, manage form submissions, inject JavaScript snippets, and much more. This is a REST-style API that uses JSON for serialization and OAuth 2 for authentication.   This document is an OpenAPI reference for the Netlify API that you can explore. For more detailed instructions for common uses, please visit the [online documentation](https://www.netlify.com/docs/api/). Visit our Community forum to join the conversation about [understanding and using Netlify's API](https://community.netlify.com/t/common-issue-understanding-and-using-netlifys-api/160).   Additionally, we have two API clients for your convenience: - [Go Client](https://github.com/netlify/open-api#go-client) - [JS Client](https://github.com/netlify/build/tree/main/packages/js-client) 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netlifyapi

import (
	"encoding/json"
	"fmt"
)

// checks if the HeroAccountSimple type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HeroAccountSimple{}

// HeroAccountSimple Simple HeroAccount model definition for basic identification
type HeroAccountSimple struct {
	// The identifier for the account
	Id string `json:"id"`
	// The name of the account
	Name string `json:"name"`
	// The slug of the account
	Slug string `json:"slug"`
	// The billing email of the account
	BillingEmail string `json:"billing_email"`
	// The admin URL for the account
	AdminUrl string `json:"admin_url"`
	// Whether the account is a credit-based plan
	IsCreditBased *bool `json:"is_credit_based,omitempty"`
	// Whether automatic top-up is currently enabled (only for credit-based plans)
	AutoTopupEnabled *bool `json:"auto_topup_enabled,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _HeroAccountSimple HeroAccountSimple

// NewHeroAccountSimple instantiates a new HeroAccountSimple object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHeroAccountSimple(id string, name string, slug string, billingEmail string, adminUrl string) *HeroAccountSimple {
	this := HeroAccountSimple{}
	this.Id = id
	this.Name = name
	this.Slug = slug
	this.BillingEmail = billingEmail
	this.AdminUrl = adminUrl
	return &this
}

// NewHeroAccountSimpleWithDefaults instantiates a new HeroAccountSimple object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHeroAccountSimpleWithDefaults() *HeroAccountSimple {
	this := HeroAccountSimple{}
	return &this
}

// GetId returns the Id field value
func (o *HeroAccountSimple) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *HeroAccountSimple) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *HeroAccountSimple) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *HeroAccountSimple) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HeroAccountSimple) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HeroAccountSimple) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *HeroAccountSimple) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *HeroAccountSimple) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *HeroAccountSimple) SetSlug(v string) {
	o.Slug = v
}

// GetBillingEmail returns the BillingEmail field value
func (o *HeroAccountSimple) GetBillingEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BillingEmail
}

// GetBillingEmailOk returns a tuple with the BillingEmail field value
// and a boolean to check if the value has been set.
func (o *HeroAccountSimple) GetBillingEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingEmail, true
}

// SetBillingEmail sets field value
func (o *HeroAccountSimple) SetBillingEmail(v string) {
	o.BillingEmail = v
}

// GetAdminUrl returns the AdminUrl field value
func (o *HeroAccountSimple) GetAdminUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AdminUrl
}

// GetAdminUrlOk returns a tuple with the AdminUrl field value
// and a boolean to check if the value has been set.
func (o *HeroAccountSimple) GetAdminUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdminUrl, true
}

// SetAdminUrl sets field value
func (o *HeroAccountSimple) SetAdminUrl(v string) {
	o.AdminUrl = v
}

// GetIsCreditBased returns the IsCreditBased field value if set, zero value otherwise.
func (o *HeroAccountSimple) GetIsCreditBased() bool {
	if o == nil || IsNil(o.IsCreditBased) {
		var ret bool
		return ret
	}
	return *o.IsCreditBased
}

// GetIsCreditBasedOk returns a tuple with the IsCreditBased field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeroAccountSimple) GetIsCreditBasedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCreditBased) {
		return nil, false
	}
	return o.IsCreditBased, true
}

// HasIsCreditBased returns a boolean if a field has been set.
func (o *HeroAccountSimple) HasIsCreditBased() bool {
	if o != nil && !IsNil(o.IsCreditBased) {
		return true
	}

	return false
}

// SetIsCreditBased gets a reference to the given bool and assigns it to the IsCreditBased field.
func (o *HeroAccountSimple) SetIsCreditBased(v bool) {
	o.IsCreditBased = &v
}

// GetAutoTopupEnabled returns the AutoTopupEnabled field value if set, zero value otherwise.
func (o *HeroAccountSimple) GetAutoTopupEnabled() bool {
	if o == nil || IsNil(o.AutoTopupEnabled) {
		var ret bool
		return ret
	}
	return *o.AutoTopupEnabled
}

// GetAutoTopupEnabledOk returns a tuple with the AutoTopupEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeroAccountSimple) GetAutoTopupEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoTopupEnabled) {
		return nil, false
	}
	return o.AutoTopupEnabled, true
}

// HasAutoTopupEnabled returns a boolean if a field has been set.
func (o *HeroAccountSimple) HasAutoTopupEnabled() bool {
	if o != nil && !IsNil(o.AutoTopupEnabled) {
		return true
	}

	return false
}

// SetAutoTopupEnabled gets a reference to the given bool and assigns it to the AutoTopupEnabled field.
func (o *HeroAccountSimple) SetAutoTopupEnabled(v bool) {
	o.AutoTopupEnabled = &v
}

func (o HeroAccountSimple) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HeroAccountSimple) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["slug"] = o.Slug
	toSerialize["billing_email"] = o.BillingEmail
	toSerialize["admin_url"] = o.AdminUrl
	if !IsNil(o.IsCreditBased) {
		toSerialize["is_credit_based"] = o.IsCreditBased
	}
	if !IsNil(o.AutoTopupEnabled) {
		toSerialize["auto_topup_enabled"] = o.AutoTopupEnabled
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HeroAccountSimple) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"slug",
		"billing_email",
		"admin_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHeroAccountSimple := _HeroAccountSimple{}

	err = json.Unmarshal(data, &varHeroAccountSimple)

	if err != nil {
		return err
	}

	*o = HeroAccountSimple(varHeroAccountSimple)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "billing_email")
		delete(additionalProperties, "admin_url")
		delete(additionalProperties, "is_credit_based")
		delete(additionalProperties, "auto_topup_enabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHeroAccountSimple struct {
	value *HeroAccountSimple
	isSet bool
}

func (v NullableHeroAccountSimple) Get() *HeroAccountSimple {
	return v.value
}

func (v *NullableHeroAccountSimple) Set(val *HeroAccountSimple) {
	v.value = val
	v.isSet = true
}

func (v NullableHeroAccountSimple) IsSet() bool {
	return v.isSet
}

func (v *NullableHeroAccountSimple) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHeroAccountSimple(val *HeroAccountSimple) *NullableHeroAccountSimple {
	return &NullableHeroAccountSimple{value: val, isSet: true}
}

func (v NullableHeroAccountSimple) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHeroAccountSimple) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


