/*
Netlify's API documentation

Netlify is a hosting service for the programmable web. It understands your documents and provides an API to handle atomic deploys of websites, manage form submissions, inject JavaScript snippets, and much more. This is a REST-style API that uses JSON for serialization and OAuth 2 for authentication.   This document is an OpenAPI reference for the Netlify API that you can explore. For more detailed instructions for common uses, please visit the [online documentation](https://docs.netlify.com/api/get-started/). Visit our Community forum to join the conversation about [understanding and using Netlify’s API](https://community.netlify.com/t/common-issue-understanding-and-using-netlifys-api/160).   Additionally, we have two API clients for your convenience: - [Go Client](https://github.com/netlify/open-api#go-client) - [JS Client](https://github.com/netlify/js-client) 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netlifyapi

import (
	"encoding/json"
)

// checks if the UpdateOutgoingHook type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOutgoingHook{}

// UpdateOutgoingHook struct for UpdateOutgoingHook
type UpdateOutgoingHook struct {
	// The site ID of the hook
	SiteId *string `json:"site_id,omitempty"`
	// The form ID of the hook (either form_id or form_name is required if the hook will be created for the form)
	FormId *string `json:"form_id,omitempty"`
	// The form name of the hook
	FormName *string `json:"form_name,omitempty"`
	// The name of the hook event
	Event *string `json:"event,omitempty"`
	// Additional data for the hook
	Data map[string]interface{} `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateOutgoingHook UpdateOutgoingHook

// NewUpdateOutgoingHook instantiates a new UpdateOutgoingHook object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOutgoingHook() *UpdateOutgoingHook {
	this := UpdateOutgoingHook{}
	return &this
}

// NewUpdateOutgoingHookWithDefaults instantiates a new UpdateOutgoingHook object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOutgoingHookWithDefaults() *UpdateOutgoingHook {
	this := UpdateOutgoingHook{}
	return &this
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *UpdateOutgoingHook) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOutgoingHook) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *UpdateOutgoingHook) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *UpdateOutgoingHook) SetSiteId(v string) {
	o.SiteId = &v
}

// GetFormId returns the FormId field value if set, zero value otherwise.
func (o *UpdateOutgoingHook) GetFormId() string {
	if o == nil || IsNil(o.FormId) {
		var ret string
		return ret
	}
	return *o.FormId
}

// GetFormIdOk returns a tuple with the FormId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOutgoingHook) GetFormIdOk() (*string, bool) {
	if o == nil || IsNil(o.FormId) {
		return nil, false
	}
	return o.FormId, true
}

// HasFormId returns a boolean if a field has been set.
func (o *UpdateOutgoingHook) HasFormId() bool {
	if o != nil && !IsNil(o.FormId) {
		return true
	}

	return false
}

// SetFormId gets a reference to the given string and assigns it to the FormId field.
func (o *UpdateOutgoingHook) SetFormId(v string) {
	o.FormId = &v
}

// GetFormName returns the FormName field value if set, zero value otherwise.
func (o *UpdateOutgoingHook) GetFormName() string {
	if o == nil || IsNil(o.FormName) {
		var ret string
		return ret
	}
	return *o.FormName
}

// GetFormNameOk returns a tuple with the FormName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOutgoingHook) GetFormNameOk() (*string, bool) {
	if o == nil || IsNil(o.FormName) {
		return nil, false
	}
	return o.FormName, true
}

// HasFormName returns a boolean if a field has been set.
func (o *UpdateOutgoingHook) HasFormName() bool {
	if o != nil && !IsNil(o.FormName) {
		return true
	}

	return false
}

// SetFormName gets a reference to the given string and assigns it to the FormName field.
func (o *UpdateOutgoingHook) SetFormName(v string) {
	o.FormName = &v
}

// GetEvent returns the Event field value if set, zero value otherwise.
func (o *UpdateOutgoingHook) GetEvent() string {
	if o == nil || IsNil(o.Event) {
		var ret string
		return ret
	}
	return *o.Event
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOutgoingHook) GetEventOk() (*string, bool) {
	if o == nil || IsNil(o.Event) {
		return nil, false
	}
	return o.Event, true
}

// HasEvent returns a boolean if a field has been set.
func (o *UpdateOutgoingHook) HasEvent() bool {
	if o != nil && !IsNil(o.Event) {
		return true
	}

	return false
}

// SetEvent gets a reference to the given string and assigns it to the Event field.
func (o *UpdateOutgoingHook) SetEvent(v string) {
	o.Event = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UpdateOutgoingHook) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOutgoingHook) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UpdateOutgoingHook) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *UpdateOutgoingHook) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o UpdateOutgoingHook) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOutgoingHook) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SiteId) {
		toSerialize["site_id"] = o.SiteId
	}
	if !IsNil(o.FormId) {
		toSerialize["form_id"] = o.FormId
	}
	if !IsNil(o.FormName) {
		toSerialize["form_name"] = o.FormName
	}
	if !IsNil(o.Event) {
		toSerialize["event"] = o.Event
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateOutgoingHook) UnmarshalJSON(data []byte) (err error) {
	varUpdateOutgoingHook := _UpdateOutgoingHook{}

	err = json.Unmarshal(data, &varUpdateOutgoingHook)

	if err != nil {
		return err
	}

	*o = UpdateOutgoingHook(varUpdateOutgoingHook)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "site_id")
		delete(additionalProperties, "form_id")
		delete(additionalProperties, "form_name")
		delete(additionalProperties, "event")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateOutgoingHook struct {
	value *UpdateOutgoingHook
	isSet bool
}

func (v NullableUpdateOutgoingHook) Get() *UpdateOutgoingHook {
	return v.value
}

func (v *NullableUpdateOutgoingHook) Set(val *UpdateOutgoingHook) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOutgoingHook) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOutgoingHook) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOutgoingHook(val *UpdateOutgoingHook) *NullableUpdateOutgoingHook {
	return &NullableUpdateOutgoingHook{value: val, isSet: true}
}

func (v NullableUpdateOutgoingHook) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOutgoingHook) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


