// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/terraform-provider-netlify/internal/models"
)

// CancelSiteDeployReader is a Reader for the CancelSiteDeploy structure.
type CancelSiteDeployReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CancelSiteDeployReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCancelSiteDeployCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCancelSiteDeployDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCancelSiteDeployCreated creates a CancelSiteDeployCreated with default headers values
func NewCancelSiteDeployCreated() *CancelSiteDeployCreated {
	return &CancelSiteDeployCreated{}
}

/*
CancelSiteDeployCreated describes a response with status code 201, with default header values.

Cancelled
*/
type CancelSiteDeployCreated struct {
	Payload *models.Deploy
}

// IsSuccess returns true when this cancel site deploy created response has a 2xx status code
func (o *CancelSiteDeployCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this cancel site deploy created response has a 3xx status code
func (o *CancelSiteDeployCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cancel site deploy created response has a 4xx status code
func (o *CancelSiteDeployCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this cancel site deploy created response has a 5xx status code
func (o *CancelSiteDeployCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this cancel site deploy created response a status code equal to that given
func (o *CancelSiteDeployCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the cancel site deploy created response
func (o *CancelSiteDeployCreated) Code() int {
	return 201
}

func (o *CancelSiteDeployCreated) Error() string {
	return fmt.Sprintf("[POST /deploys/{deploy_id}/cancel][%d] cancelSiteDeployCreated  %+v", 201, o.Payload)
}

func (o *CancelSiteDeployCreated) String() string {
	return fmt.Sprintf("[POST /deploys/{deploy_id}/cancel][%d] cancelSiteDeployCreated  %+v", 201, o.Payload)
}

func (o *CancelSiteDeployCreated) GetPayload() *models.Deploy {
	return o.Payload
}

func (o *CancelSiteDeployCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Deploy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCancelSiteDeployDefault creates a CancelSiteDeployDefault with default headers values
func NewCancelSiteDeployDefault(code int) *CancelSiteDeployDefault {
	return &CancelSiteDeployDefault{
		_statusCode: code,
	}
}

/*
CancelSiteDeployDefault describes a response with status code -1, with default header values.

error
*/
type CancelSiteDeployDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this cancel site deploy default response has a 2xx status code
func (o *CancelSiteDeployDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this cancel site deploy default response has a 3xx status code
func (o *CancelSiteDeployDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this cancel site deploy default response has a 4xx status code
func (o *CancelSiteDeployDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this cancel site deploy default response has a 5xx status code
func (o *CancelSiteDeployDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this cancel site deploy default response a status code equal to that given
func (o *CancelSiteDeployDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the cancel site deploy default response
func (o *CancelSiteDeployDefault) Code() int {
	return o._statusCode
}

func (o *CancelSiteDeployDefault) Error() string {
	return fmt.Sprintf("[POST /deploys/{deploy_id}/cancel][%d] cancelSiteDeploy default  %+v", o._statusCode, o.Payload)
}

func (o *CancelSiteDeployDefault) String() string {
	return fmt.Sprintf("[POST /deploys/{deploy_id}/cancel][%d] cancelSiteDeploy default  %+v", o._statusCode, o.Payload)
}

func (o *CancelSiteDeployDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *CancelSiteDeployDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
