// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/terraform-provider-netlify/internal/models"
)

// DeleteSiteDevServerHookReader is a Reader for the DeleteSiteDevServerHook structure.
type DeleteSiteDevServerHookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSiteDevServerHookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteSiteDevServerHookNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteSiteDevServerHookDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteSiteDevServerHookNoContent creates a DeleteSiteDevServerHookNoContent with default headers values
func NewDeleteSiteDevServerHookNoContent() *DeleteSiteDevServerHookNoContent {
	return &DeleteSiteDevServerHookNoContent{}
}

/*
DeleteSiteDevServerHookNoContent describes a response with status code 204, with default header values.

No content
*/
type DeleteSiteDevServerHookNoContent struct {
}

// IsSuccess returns true when this delete site dev server hook no content response has a 2xx status code
func (o *DeleteSiteDevServerHookNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete site dev server hook no content response has a 3xx status code
func (o *DeleteSiteDevServerHookNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete site dev server hook no content response has a 4xx status code
func (o *DeleteSiteDevServerHookNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete site dev server hook no content response has a 5xx status code
func (o *DeleteSiteDevServerHookNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete site dev server hook no content response a status code equal to that given
func (o *DeleteSiteDevServerHookNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete site dev server hook no content response
func (o *DeleteSiteDevServerHookNoContent) Code() int {
	return 204
}

func (o *DeleteSiteDevServerHookNoContent) Error() string {
	return fmt.Sprintf("[DELETE /sites/{site_id}/dev_server_hooks/{id}][%d] deleteSiteDevServerHookNoContent ", 204)
}

func (o *DeleteSiteDevServerHookNoContent) String() string {
	return fmt.Sprintf("[DELETE /sites/{site_id}/dev_server_hooks/{id}][%d] deleteSiteDevServerHookNoContent ", 204)
}

func (o *DeleteSiteDevServerHookNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSiteDevServerHookDefault creates a DeleteSiteDevServerHookDefault with default headers values
func NewDeleteSiteDevServerHookDefault(code int) *DeleteSiteDevServerHookDefault {
	return &DeleteSiteDevServerHookDefault{
		_statusCode: code,
	}
}

/*
DeleteSiteDevServerHookDefault describes a response with status code -1, with default header values.

error
*/
type DeleteSiteDevServerHookDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this delete site dev server hook default response has a 2xx status code
func (o *DeleteSiteDevServerHookDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete site dev server hook default response has a 3xx status code
func (o *DeleteSiteDevServerHookDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete site dev server hook default response has a 4xx status code
func (o *DeleteSiteDevServerHookDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete site dev server hook default response has a 5xx status code
func (o *DeleteSiteDevServerHookDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete site dev server hook default response a status code equal to that given
func (o *DeleteSiteDevServerHookDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete site dev server hook default response
func (o *DeleteSiteDevServerHookDefault) Code() int {
	return o._statusCode
}

func (o *DeleteSiteDevServerHookDefault) Error() string {
	return fmt.Sprintf("[DELETE /sites/{site_id}/dev_server_hooks/{id}][%d] deleteSiteDevServerHook default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteSiteDevServerHookDefault) String() string {
	return fmt.Sprintf("[DELETE /sites/{site_id}/dev_server_hooks/{id}][%d] deleteSiteDevServerHook default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteSiteDevServerHookDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteSiteDevServerHookDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
