// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/terraform-provider-netlify/internal/models"
)

// GetDNSRecordsReader is a Reader for the GetDNSRecords structure.
type GetDNSRecordsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDNSRecordsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDNSRecordsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetDNSRecordsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDNSRecordsOK creates a GetDNSRecordsOK with default headers values
func NewGetDNSRecordsOK() *GetDNSRecordsOK {
	return &GetDNSRecordsOK{}
}

/*
GetDNSRecordsOK describes a response with status code 200, with default header values.

get all DNS records for a single DNS zone
*/
type GetDNSRecordsOK struct {
	Payload models.DNSRecords
}

// IsSuccess returns true when this get Dns records o k response has a 2xx status code
func (o *GetDNSRecordsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Dns records o k response has a 3xx status code
func (o *GetDNSRecordsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Dns records o k response has a 4xx status code
func (o *GetDNSRecordsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Dns records o k response has a 5xx status code
func (o *GetDNSRecordsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Dns records o k response a status code equal to that given
func (o *GetDNSRecordsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Dns records o k response
func (o *GetDNSRecordsOK) Code() int {
	return 200
}

func (o *GetDNSRecordsOK) Error() string {
	return fmt.Sprintf("[GET /dns_zones/{zone_id}/dns_records][%d] getDnsRecordsOK  %+v", 200, o.Payload)
}

func (o *GetDNSRecordsOK) String() string {
	return fmt.Sprintf("[GET /dns_zones/{zone_id}/dns_records][%d] getDnsRecordsOK  %+v", 200, o.Payload)
}

func (o *GetDNSRecordsOK) GetPayload() models.DNSRecords {
	return o.Payload
}

func (o *GetDNSRecordsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDNSRecordsDefault creates a GetDNSRecordsDefault with default headers values
func NewGetDNSRecordsDefault(code int) *GetDNSRecordsDefault {
	return &GetDNSRecordsDefault{
		_statusCode: code,
	}
}

/*
GetDNSRecordsDefault describes a response with status code -1, with default header values.

error
*/
type GetDNSRecordsDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this get Dns records default response has a 2xx status code
func (o *GetDNSRecordsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get Dns records default response has a 3xx status code
func (o *GetDNSRecordsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get Dns records default response has a 4xx status code
func (o *GetDNSRecordsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get Dns records default response has a 5xx status code
func (o *GetDNSRecordsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get Dns records default response a status code equal to that given
func (o *GetDNSRecordsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get Dns records default response
func (o *GetDNSRecordsDefault) Code() int {
	return o._statusCode
}

func (o *GetDNSRecordsDefault) Error() string {
	return fmt.Sprintf("[GET /dns_zones/{zone_id}/dns_records][%d] getDnsRecords default  %+v", o._statusCode, o.Payload)
}

func (o *GetDNSRecordsDefault) String() string {
	return fmt.Sprintf("[GET /dns_zones/{zone_id}/dns_records][%d] getDnsRecords default  %+v", o._statusCode, o.Payload)
}

func (o *GetDNSRecordsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDNSRecordsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
