// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/terraform-provider-netlify/internal/models"
)

// GetDeployKeyReader is a Reader for the GetDeployKey structure.
type GetDeployKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeployKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeployKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetDeployKeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDeployKeyOK creates a GetDeployKeyOK with default headers values
func NewGetDeployKeyOK() *GetDeployKeyOK {
	return &GetDeployKeyOK{}
}

/*
GetDeployKeyOK describes a response with status code 200, with default header values.

OK
*/
type GetDeployKeyOK struct {
	Payload *models.DeployKey
}

// IsSuccess returns true when this get deploy key o k response has a 2xx status code
func (o *GetDeployKeyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get deploy key o k response has a 3xx status code
func (o *GetDeployKeyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get deploy key o k response has a 4xx status code
func (o *GetDeployKeyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get deploy key o k response has a 5xx status code
func (o *GetDeployKeyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get deploy key o k response a status code equal to that given
func (o *GetDeployKeyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get deploy key o k response
func (o *GetDeployKeyOK) Code() int {
	return 200
}

func (o *GetDeployKeyOK) Error() string {
	return fmt.Sprintf("[GET /deploy_keys/{key_id}][%d] getDeployKeyOK  %+v", 200, o.Payload)
}

func (o *GetDeployKeyOK) String() string {
	return fmt.Sprintf("[GET /deploy_keys/{key_id}][%d] getDeployKeyOK  %+v", 200, o.Payload)
}

func (o *GetDeployKeyOK) GetPayload() *models.DeployKey {
	return o.Payload
}

func (o *GetDeployKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeployKey)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDeployKeyDefault creates a GetDeployKeyDefault with default headers values
func NewGetDeployKeyDefault(code int) *GetDeployKeyDefault {
	return &GetDeployKeyDefault{
		_statusCode: code,
	}
}

/*
GetDeployKeyDefault describes a response with status code -1, with default header values.

error
*/
type GetDeployKeyDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this get deploy key default response has a 2xx status code
func (o *GetDeployKeyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get deploy key default response has a 3xx status code
func (o *GetDeployKeyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get deploy key default response has a 4xx status code
func (o *GetDeployKeyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get deploy key default response has a 5xx status code
func (o *GetDeployKeyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get deploy key default response a status code equal to that given
func (o *GetDeployKeyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get deploy key default response
func (o *GetDeployKeyDefault) Code() int {
	return o._statusCode
}

func (o *GetDeployKeyDefault) Error() string {
	return fmt.Sprintf("[GET /deploy_keys/{key_id}][%d] getDeployKey default  %+v", o._statusCode, o.Payload)
}

func (o *GetDeployKeyDefault) String() string {
	return fmt.Sprintf("[GET /deploy_keys/{key_id}][%d] getDeployKey default  %+v", o._statusCode, o.Payload)
}

func (o *GetDeployKeyDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDeployKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
