// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/terraform-provider-netlify/internal/models"
)

// GetDNSZonesReader is a Reader for the GetDNSZones structure.
type GetDNSZonesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDNSZonesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDNSZonesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetDNSZonesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDNSZonesOK creates a GetDNSZonesOK with default headers values
func NewGetDNSZonesOK() *GetDNSZonesOK {
	return &GetDNSZonesOK{}
}

/*
GetDNSZonesOK describes a response with status code 200, with default header values.

get all DNS zones the user has access to
*/
type GetDNSZonesOK struct {
	Payload models.DNSZones
}

// IsSuccess returns true when this get Dns zones o k response has a 2xx status code
func (o *GetDNSZonesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Dns zones o k response has a 3xx status code
func (o *GetDNSZonesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Dns zones o k response has a 4xx status code
func (o *GetDNSZonesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Dns zones o k response has a 5xx status code
func (o *GetDNSZonesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Dns zones o k response a status code equal to that given
func (o *GetDNSZonesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Dns zones o k response
func (o *GetDNSZonesOK) Code() int {
	return 200
}

func (o *GetDNSZonesOK) Error() string {
	return fmt.Sprintf("[GET /dns_zones][%d] getDnsZonesOK  %+v", 200, o.Payload)
}

func (o *GetDNSZonesOK) String() string {
	return fmt.Sprintf("[GET /dns_zones][%d] getDnsZonesOK  %+v", 200, o.Payload)
}

func (o *GetDNSZonesOK) GetPayload() models.DNSZones {
	return o.Payload
}

func (o *GetDNSZonesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDNSZonesDefault creates a GetDNSZonesDefault with default headers values
func NewGetDNSZonesDefault(code int) *GetDNSZonesDefault {
	return &GetDNSZonesDefault{
		_statusCode: code,
	}
}

/*
GetDNSZonesDefault describes a response with status code -1, with default header values.

error
*/
type GetDNSZonesDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this get Dns zones default response has a 2xx status code
func (o *GetDNSZonesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get Dns zones default response has a 3xx status code
func (o *GetDNSZonesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get Dns zones default response has a 4xx status code
func (o *GetDNSZonesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get Dns zones default response has a 5xx status code
func (o *GetDNSZonesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get Dns zones default response a status code equal to that given
func (o *GetDNSZonesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get Dns zones default response
func (o *GetDNSZonesDefault) Code() int {
	return o._statusCode
}

func (o *GetDNSZonesDefault) Error() string {
	return fmt.Sprintf("[GET /dns_zones][%d] getDnsZones default  %+v", o._statusCode, o.Payload)
}

func (o *GetDNSZonesDefault) String() string {
	return fmt.Sprintf("[GET /dns_zones][%d] getDnsZones default  %+v", o._statusCode, o.Payload)
}

func (o *GetDNSZonesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDNSZonesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
