// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/terraform-provider-netlify/internal/models"
)

// GetSiteBuildReader is a Reader for the GetSiteBuild structure.
type GetSiteBuildReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSiteBuildReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSiteBuildOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetSiteBuildDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSiteBuildOK creates a GetSiteBuildOK with default headers values
func NewGetSiteBuildOK() *GetSiteBuildOK {
	return &GetSiteBuildOK{}
}

/*
GetSiteBuildOK describes a response with status code 200, with default header values.

OK
*/
type GetSiteBuildOK struct {
	Payload *models.Build
}

// IsSuccess returns true when this get site build o k response has a 2xx status code
func (o *GetSiteBuildOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get site build o k response has a 3xx status code
func (o *GetSiteBuildOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get site build o k response has a 4xx status code
func (o *GetSiteBuildOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get site build o k response has a 5xx status code
func (o *GetSiteBuildOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get site build o k response a status code equal to that given
func (o *GetSiteBuildOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get site build o k response
func (o *GetSiteBuildOK) Code() int {
	return 200
}

func (o *GetSiteBuildOK) Error() string {
	return fmt.Sprintf("[GET /builds/{build_id}][%d] getSiteBuildOK  %+v", 200, o.Payload)
}

func (o *GetSiteBuildOK) String() string {
	return fmt.Sprintf("[GET /builds/{build_id}][%d] getSiteBuildOK  %+v", 200, o.Payload)
}

func (o *GetSiteBuildOK) GetPayload() *models.Build {
	return o.Payload
}

func (o *GetSiteBuildOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Build)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSiteBuildDefault creates a GetSiteBuildDefault with default headers values
func NewGetSiteBuildDefault(code int) *GetSiteBuildDefault {
	return &GetSiteBuildDefault{
		_statusCode: code,
	}
}

/*
GetSiteBuildDefault describes a response with status code -1, with default header values.

error
*/
type GetSiteBuildDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this get site build default response has a 2xx status code
func (o *GetSiteBuildDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get site build default response has a 3xx status code
func (o *GetSiteBuildDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get site build default response has a 4xx status code
func (o *GetSiteBuildDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get site build default response has a 5xx status code
func (o *GetSiteBuildDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get site build default response a status code equal to that given
func (o *GetSiteBuildDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get site build default response
func (o *GetSiteBuildDefault) Code() int {
	return o._statusCode
}

func (o *GetSiteBuildDefault) Error() string {
	return fmt.Sprintf("[GET /builds/{build_id}][%d] getSiteBuild default  %+v", o._statusCode, o.Payload)
}

func (o *GetSiteBuildDefault) String() string {
	return fmt.Sprintf("[GET /builds/{build_id}][%d] getSiteBuild default  %+v", o._statusCode, o.Payload)
}

func (o *GetSiteBuildDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetSiteBuildDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
