// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/terraform-provider-netlify/internal/models"
)

// ListPaymentMethodsForUserReader is a Reader for the ListPaymentMethodsForUser structure.
type ListPaymentMethodsForUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPaymentMethodsForUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListPaymentMethodsForUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListPaymentMethodsForUserDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListPaymentMethodsForUserOK creates a ListPaymentMethodsForUserOK with default headers values
func NewListPaymentMethodsForUserOK() *ListPaymentMethodsForUserOK {
	return &ListPaymentMethodsForUserOK{}
}

/*
ListPaymentMethodsForUserOK describes a response with status code 200, with default header values.

OK
*/
type ListPaymentMethodsForUserOK struct {
	Payload []*models.PaymentMethod
}

// IsSuccess returns true when this list payment methods for user o k response has a 2xx status code
func (o *ListPaymentMethodsForUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list payment methods for user o k response has a 3xx status code
func (o *ListPaymentMethodsForUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list payment methods for user o k response has a 4xx status code
func (o *ListPaymentMethodsForUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list payment methods for user o k response has a 5xx status code
func (o *ListPaymentMethodsForUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list payment methods for user o k response a status code equal to that given
func (o *ListPaymentMethodsForUserOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list payment methods for user o k response
func (o *ListPaymentMethodsForUserOK) Code() int {
	return 200
}

func (o *ListPaymentMethodsForUserOK) Error() string {
	return fmt.Sprintf("[GET /billing/payment_methods][%d] listPaymentMethodsForUserOK  %+v", 200, o.Payload)
}

func (o *ListPaymentMethodsForUserOK) String() string {
	return fmt.Sprintf("[GET /billing/payment_methods][%d] listPaymentMethodsForUserOK  %+v", 200, o.Payload)
}

func (o *ListPaymentMethodsForUserOK) GetPayload() []*models.PaymentMethod {
	return o.Payload
}

func (o *ListPaymentMethodsForUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPaymentMethodsForUserDefault creates a ListPaymentMethodsForUserDefault with default headers values
func NewListPaymentMethodsForUserDefault(code int) *ListPaymentMethodsForUserDefault {
	return &ListPaymentMethodsForUserDefault{
		_statusCode: code,
	}
}

/*
ListPaymentMethodsForUserDefault describes a response with status code -1, with default header values.

error
*/
type ListPaymentMethodsForUserDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this list payment methods for user default response has a 2xx status code
func (o *ListPaymentMethodsForUserDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list payment methods for user default response has a 3xx status code
func (o *ListPaymentMethodsForUserDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list payment methods for user default response has a 4xx status code
func (o *ListPaymentMethodsForUserDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list payment methods for user default response has a 5xx status code
func (o *ListPaymentMethodsForUserDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list payment methods for user default response a status code equal to that given
func (o *ListPaymentMethodsForUserDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list payment methods for user default response
func (o *ListPaymentMethodsForUserDefault) Code() int {
	return o._statusCode
}

func (o *ListPaymentMethodsForUserDefault) Error() string {
	return fmt.Sprintf("[GET /billing/payment_methods][%d] listPaymentMethodsForUser default  %+v", o._statusCode, o.Payload)
}

func (o *ListPaymentMethodsForUserDefault) String() string {
	return fmt.Sprintf("[GET /billing/payment_methods][%d] listPaymentMethodsForUser default  %+v", o._statusCode, o.Payload)
}

func (o *ListPaymentMethodsForUserDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListPaymentMethodsForUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
