// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/terraform-provider-netlify/internal/models"
)

// ListSiteDeployedBranchesReader is a Reader for the ListSiteDeployedBranches structure.
type ListSiteDeployedBranchesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSiteDeployedBranchesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSiteDeployedBranchesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListSiteDeployedBranchesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListSiteDeployedBranchesOK creates a ListSiteDeployedBranchesOK with default headers values
func NewListSiteDeployedBranchesOK() *ListSiteDeployedBranchesOK {
	return &ListSiteDeployedBranchesOK{}
}

/*
ListSiteDeployedBranchesOK describes a response with status code 200, with default header values.

OK
*/
type ListSiteDeployedBranchesOK struct {
	Payload []*models.DeployedBranch
}

// IsSuccess returns true when this list site deployed branches o k response has a 2xx status code
func (o *ListSiteDeployedBranchesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list site deployed branches o k response has a 3xx status code
func (o *ListSiteDeployedBranchesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list site deployed branches o k response has a 4xx status code
func (o *ListSiteDeployedBranchesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list site deployed branches o k response has a 5xx status code
func (o *ListSiteDeployedBranchesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list site deployed branches o k response a status code equal to that given
func (o *ListSiteDeployedBranchesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list site deployed branches o k response
func (o *ListSiteDeployedBranchesOK) Code() int {
	return 200
}

func (o *ListSiteDeployedBranchesOK) Error() string {
	return fmt.Sprintf("[GET /sites/{site_id}/deployed-branches][%d] listSiteDeployedBranchesOK  %+v", 200, o.Payload)
}

func (o *ListSiteDeployedBranchesOK) String() string {
	return fmt.Sprintf("[GET /sites/{site_id}/deployed-branches][%d] listSiteDeployedBranchesOK  %+v", 200, o.Payload)
}

func (o *ListSiteDeployedBranchesOK) GetPayload() []*models.DeployedBranch {
	return o.Payload
}

func (o *ListSiteDeployedBranchesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSiteDeployedBranchesDefault creates a ListSiteDeployedBranchesDefault with default headers values
func NewListSiteDeployedBranchesDefault(code int) *ListSiteDeployedBranchesDefault {
	return &ListSiteDeployedBranchesDefault{
		_statusCode: code,
	}
}

/*
ListSiteDeployedBranchesDefault describes a response with status code -1, with default header values.

error
*/
type ListSiteDeployedBranchesDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this list site deployed branches default response has a 2xx status code
func (o *ListSiteDeployedBranchesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list site deployed branches default response has a 3xx status code
func (o *ListSiteDeployedBranchesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list site deployed branches default response has a 4xx status code
func (o *ListSiteDeployedBranchesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list site deployed branches default response has a 5xx status code
func (o *ListSiteDeployedBranchesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list site deployed branches default response a status code equal to that given
func (o *ListSiteDeployedBranchesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list site deployed branches default response
func (o *ListSiteDeployedBranchesDefault) Code() int {
	return o._statusCode
}

func (o *ListSiteDeployedBranchesDefault) Error() string {
	return fmt.Sprintf("[GET /sites/{site_id}/deployed-branches][%d] listSiteDeployedBranches default  %+v", o._statusCode, o.Payload)
}

func (o *ListSiteDeployedBranchesDefault) String() string {
	return fmt.Sprintf("[GET /sites/{site_id}/deployed-branches][%d] listSiteDeployedBranches default  %+v", o._statusCode, o.Payload)
}

func (o *ListSiteDeployedBranchesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListSiteDeployedBranchesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
