// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/terraform-provider-netlify/internal/models"
)

// UpdateServiceInstanceReader is a Reader for the UpdateServiceInstance structure.
type UpdateServiceInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateServiceInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateServiceInstanceNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdateServiceInstanceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateServiceInstanceNoContent creates a UpdateServiceInstanceNoContent with default headers values
func NewUpdateServiceInstanceNoContent() *UpdateServiceInstanceNoContent {
	return &UpdateServiceInstanceNoContent{}
}

/*
UpdateServiceInstanceNoContent describes a response with status code 204, with default header values.

No Content
*/
type UpdateServiceInstanceNoContent struct {
}

// IsSuccess returns true when this update service instance no content response has a 2xx status code
func (o *UpdateServiceInstanceNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update service instance no content response has a 3xx status code
func (o *UpdateServiceInstanceNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update service instance no content response has a 4xx status code
func (o *UpdateServiceInstanceNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this update service instance no content response has a 5xx status code
func (o *UpdateServiceInstanceNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this update service instance no content response a status code equal to that given
func (o *UpdateServiceInstanceNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the update service instance no content response
func (o *UpdateServiceInstanceNoContent) Code() int {
	return 204
}

func (o *UpdateServiceInstanceNoContent) Error() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/services/{addon}/instances/{instance_id}][%d] updateServiceInstanceNoContent ", 204)
}

func (o *UpdateServiceInstanceNoContent) String() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/services/{addon}/instances/{instance_id}][%d] updateServiceInstanceNoContent ", 204)
}

func (o *UpdateServiceInstanceNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateServiceInstanceDefault creates a UpdateServiceInstanceDefault with default headers values
func NewUpdateServiceInstanceDefault(code int) *UpdateServiceInstanceDefault {
	return &UpdateServiceInstanceDefault{
		_statusCode: code,
	}
}

/*
UpdateServiceInstanceDefault describes a response with status code -1, with default header values.

error
*/
type UpdateServiceInstanceDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this update service instance default response has a 2xx status code
func (o *UpdateServiceInstanceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this update service instance default response has a 3xx status code
func (o *UpdateServiceInstanceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this update service instance default response has a 4xx status code
func (o *UpdateServiceInstanceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this update service instance default response has a 5xx status code
func (o *UpdateServiceInstanceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this update service instance default response a status code equal to that given
func (o *UpdateServiceInstanceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the update service instance default response
func (o *UpdateServiceInstanceDefault) Code() int {
	return o._statusCode
}

func (o *UpdateServiceInstanceDefault) Error() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/services/{addon}/instances/{instance_id}][%d] updateServiceInstance default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateServiceInstanceDefault) String() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/services/{addon}/instances/{instance_id}][%d] updateServiceInstance default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateServiceInstanceDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateServiceInstanceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
