// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/terraform-provider-netlify/internal/models"
)

// UpdateSplitTestReader is a Reader for the UpdateSplitTest structure.
type UpdateSplitTestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSplitTestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdateSplitTestCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdateSplitTestDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateSplitTestCreated creates a UpdateSplitTestCreated with default headers values
func NewUpdateSplitTestCreated() *UpdateSplitTestCreated {
	return &UpdateSplitTestCreated{}
}

/*
UpdateSplitTestCreated describes a response with status code 201, with default header values.

Created
*/
type UpdateSplitTestCreated struct {
	Payload *models.SplitTest
}

// IsSuccess returns true when this update split test created response has a 2xx status code
func (o *UpdateSplitTestCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update split test created response has a 3xx status code
func (o *UpdateSplitTestCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update split test created response has a 4xx status code
func (o *UpdateSplitTestCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this update split test created response has a 5xx status code
func (o *UpdateSplitTestCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this update split test created response a status code equal to that given
func (o *UpdateSplitTestCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the update split test created response
func (o *UpdateSplitTestCreated) Code() int {
	return 201
}

func (o *UpdateSplitTestCreated) Error() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/traffic_splits/{split_test_id}][%d] updateSplitTestCreated  %+v", 201, o.Payload)
}

func (o *UpdateSplitTestCreated) String() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/traffic_splits/{split_test_id}][%d] updateSplitTestCreated  %+v", 201, o.Payload)
}

func (o *UpdateSplitTestCreated) GetPayload() *models.SplitTest {
	return o.Payload
}

func (o *UpdateSplitTestCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SplitTest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateSplitTestDefault creates a UpdateSplitTestDefault with default headers values
func NewUpdateSplitTestDefault(code int) *UpdateSplitTestDefault {
	return &UpdateSplitTestDefault{
		_statusCode: code,
	}
}

/*
UpdateSplitTestDefault describes a response with status code -1, with default header values.

error
*/
type UpdateSplitTestDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this update split test default response has a 2xx status code
func (o *UpdateSplitTestDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this update split test default response has a 3xx status code
func (o *UpdateSplitTestDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this update split test default response has a 4xx status code
func (o *UpdateSplitTestDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this update split test default response has a 5xx status code
func (o *UpdateSplitTestDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this update split test default response a status code equal to that given
func (o *UpdateSplitTestDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the update split test default response
func (o *UpdateSplitTestDefault) Code() int {
	return o._statusCode
}

func (o *UpdateSplitTestDefault) Error() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/traffic_splits/{split_test_id}][%d] updateSplitTest default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateSplitTestDefault) String() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/traffic_splits/{split_test_id}][%d] updateSplitTest default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateSplitTestDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateSplitTestDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
