// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/terraform-provider-netlify/internal/models"
)

// UploadDeployFunctionReader is a Reader for the UploadDeployFunction structure.
type UploadDeployFunctionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadDeployFunctionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUploadDeployFunctionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUploadDeployFunctionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUploadDeployFunctionOK creates a UploadDeployFunctionOK with default headers values
func NewUploadDeployFunctionOK() *UploadDeployFunctionOK {
	return &UploadDeployFunctionOK{}
}

/*
UploadDeployFunctionOK describes a response with status code 200, with default header values.

OK
*/
type UploadDeployFunctionOK struct {
	Payload *models.Function
}

// IsSuccess returns true when this upload deploy function o k response has a 2xx status code
func (o *UploadDeployFunctionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this upload deploy function o k response has a 3xx status code
func (o *UploadDeployFunctionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload deploy function o k response has a 4xx status code
func (o *UploadDeployFunctionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload deploy function o k response has a 5xx status code
func (o *UploadDeployFunctionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this upload deploy function o k response a status code equal to that given
func (o *UploadDeployFunctionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the upload deploy function o k response
func (o *UploadDeployFunctionOK) Code() int {
	return 200
}

func (o *UploadDeployFunctionOK) Error() string {
	return fmt.Sprintf("[PUT /deploys/{deploy_id}/functions/{name}][%d] uploadDeployFunctionOK  %+v", 200, o.Payload)
}

func (o *UploadDeployFunctionOK) String() string {
	return fmt.Sprintf("[PUT /deploys/{deploy_id}/functions/{name}][%d] uploadDeployFunctionOK  %+v", 200, o.Payload)
}

func (o *UploadDeployFunctionOK) GetPayload() *models.Function {
	return o.Payload
}

func (o *UploadDeployFunctionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Function)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUploadDeployFunctionDefault creates a UploadDeployFunctionDefault with default headers values
func NewUploadDeployFunctionDefault(code int) *UploadDeployFunctionDefault {
	return &UploadDeployFunctionDefault{
		_statusCode: code,
	}
}

/*
UploadDeployFunctionDefault describes a response with status code -1, with default header values.

error
*/
type UploadDeployFunctionDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this upload deploy function default response has a 2xx status code
func (o *UploadDeployFunctionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this upload deploy function default response has a 3xx status code
func (o *UploadDeployFunctionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this upload deploy function default response has a 4xx status code
func (o *UploadDeployFunctionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this upload deploy function default response has a 5xx status code
func (o *UploadDeployFunctionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this upload deploy function default response a status code equal to that given
func (o *UploadDeployFunctionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the upload deploy function default response
func (o *UploadDeployFunctionDefault) Code() int {
	return o._statusCode
}

func (o *UploadDeployFunctionDefault) Error() string {
	return fmt.Sprintf("[PUT /deploys/{deploy_id}/functions/{name}][%d] uploadDeployFunction default  %+v", o._statusCode, o.Payload)
}

func (o *UploadDeployFunctionDefault) String() string {
	return fmt.Sprintf("[PUT /deploys/{deploy_id}/functions/{name}][%d] uploadDeployFunction default  %+v", o._statusCode, o.Payload)
}

func (o *UploadDeployFunctionDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *UploadDeployFunctionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
